### ISSUE TITLE
English, please!

### ISSUE THREAD

**Issue by akuckartz** [Informatievlaanderen/Data.Vlaanderen.be#64]
I would like to follow these issues, but I do not understand. Can you please use English language  - or at least provide summaries in English?

Happy new year from Germany!

**Comment by jensscheerlinck** [comment]
Hello Andreas,

Thank you for your comment.
The reason the issues are in Dutch is because currently all working group members are Dutch speaking. Therefore it is not easy to enforce English as the default language.

For more context on the project in English I can refer you to [this presentation](https://joinup.ec.europa.eu/sites/default/files/inline-files/SEMIC_Linked%20Base%20Registries%20as%20a%20key%20enabler%20in%20Flanders%20-%200_7.pdf).
